// <auto-generated />
using KicksChronicles_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KicksChronicles_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230927153109_SeedDbWithShoes")]
    partial class SeedDbWithShoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KicksChronicles_API.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Just do it",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/nike.svg",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Become Legendary",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/jordan.svg",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Impossible is Nothing",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/adidas-1.svg",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 4,
                            Description = "We Are All Stars",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/converse.svg",
                            Name = "Converse"
                        },
                        new
                        {
                            Id = 5,
                            Description = "THE ONLY WAY IS THROUGH",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/underarmour.svg",
                            Name = "Under Armour"
                        },
                        new
                        {
                            Id = 6,
                            Description = "We Got Now",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/newbalance.svg",
                            Name = "New Balance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Keep Moving",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/anta.svg",
                            Name = "Anta"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Forever Faster",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/puma.svg",
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A sound mind is a sound body",
                            LogoURL = "https://kickschronicles.blob.core.windows.net/brandlogos/asics.svg",
                            Name = "ASICS"
                        });
                });

            modelBuilder.Entity("KicksChronicles_API.Models.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoeThumbnailURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 3,
                            Name = "Tmac 1",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/adidas/tmac1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Name = "Westbrook 0.1",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/westbrook-0.1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Name = "Jordan 1",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/air-jordan-1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            Name = "Tmac 5",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/adidas/tmac5.jpg"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            Name = "Jordan 11",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/jordan-11-spacejam.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "Tatum 1",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/tatum-1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Name = "Zion 2",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/zion-2.jpg"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Name = "Jordan 38",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/air-jordan-38.jpg"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            Name = "Westbrook 0.5",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/westbrook-0.5.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            Name = "Westbrook 0.6",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/westbrook-0.6.jpg"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 5,
                            Name = "Curry 4",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/under-armour/curry-4-2.jpg"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            Name = "Jordan 12",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/jordan/jordan-12.jpg"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            Name = "LeBron 20",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/nike/lebron-20.jpg"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            Name = "LeBron NXXT Gen",
                            ShoeThumbnailURL = "https://kickschronicles.blob.core.windows.net/nike/lebron-nxxt-gen.jpg"
                        });
                });

            modelBuilder.Entity("KicksChronicles_API.Models.Shoe", b =>
                {
                    b.HasOne("KicksChronicles_API.Models.Brand", null)
                        .WithMany("Shoes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KicksChronicles_API.Models.Brand", b =>
                {
                    b.Navigation("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
